### ISSUE TITLE
LV2 target?

### ISSUE THREAD

**Issue by mxmilkiib** [xivilay/scale-remapper#4]
With JUCE 7 comes creating LV2 plugins. Could LV2 be added as a target format? Thanks!

**Comment by xivilay** [comment]
@mxmilkiib, no problem, here is the release https://github.com/xivilay/scale-remapper/releases/tag/v0.5.2
However I don't have any LV2 compatible host, so I didn't check if it is working.

**Comment by dromer** [comment]
Try Carla? (standalone plugin host and cross-platform)

**Comment by juanriccio** [comment]
Reaper is now supporting lv2 on Windows too (and CLAP, in current prereleases)

**Comment by dromer** [comment]
carla, ardour, reaper, mixxx, zrythm. plenty cross platform lv2 hosts to choose from.
